name: car_service_app
description: A mobile app for booking car services.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Backend and data handling
  http: ^0.13.6
  shared_preferences: ^2.2.0

  # UI enhancements
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
